### ISSUE TITLE
Error:  Failed to register and enroll JohnDoe1: 

### ISSUE THREAD

**Issue by vamsibassetty08** [IBM-Blockchain/SDK-Demo#13]
Error:  Failed to register and enroll JohnDoe1: Error: proto: can't skip unknown wire type 7 for protos.Attribut

in config.json, the username present is "JohnDoe1" and when i run helloblockchain.js, I'm getting failed to register and enroll error. Do i need to change the username?? I even tried with my user name but still same error.

**Comment by MHamza81** [comment]
@vamsibassetty08  I am facing the same issue. If you have solved it please help me with it.

**Comment by ratnakar-asara** [comment]
@vamsibassetty08 
A couple of questions 
- What node version are you using ?
- Are you using your old network or a new network created after November 9th ?
  (If the network is created before November 9th I would suggest you to use switch to branch v0.5 and follow the instructions as per README)

I reverted `JohnDoe1` to original value `JohnDoe`, Seems like you were using some old changes.
Could you pull the latest changes and give a try agian and let us know.

**Comment by vamsibassetty08** [comment]
@ratnakar-asara 

I'm having node version 6.9.1 & regarding second query, I got below version details of hfc.

..\SDK-Demo>npm ls hfc
Hello-Blockchain@0.0.1 ..\SDK-Demo
`-- hfc@0.5.4

By the way, I still get the same error with either JohnDoe1 or JohnDoe

**Comment by ratnakar-asara** [comment]
@vamsibassetty08 It seems you are using old Bluemix network with fabric0.5. If so please switch to branch 0.5 from github and use the node program and the instructions available for the same.

The program given here in master branch works only on Fabric0.6 , that means works with the Bluemix Blockchain service created after November 9th 2016.

**Comment by vamsibassetty08** [comment]
@ratnakar-asara As per confirmation, I'm already on 0.5.

..\SDK-Demo>git checkout v0.5
M       ServiceCredentials.json
M       config.json
Already on 'v0.5'
Your branch is up-to-date with 'origin/v0.5'.

Please let me know if you need any additional information.

**Comment by ratnakar-asara** [comment]
@vamsibassetty08 , Could you try with the latest Bluemix Blockchain service and latest code updated in this repo.

**Comment by vamsibassetty08** [comment]
Sure will try & get back

Sent from my Verizon Wireless 4G LTE DROID
On Nov 21, 2016 11:59 AM, Ratnakar notifications@github.com wrote:

@vamsibassetty08https://github.com/vamsibassetty08 , Could you try with the latest Bluemix Blockchain service and latest code updated in this repo.

**Comment by javierpruedas** [comment]
Hello @vamsibassetty08 

I am facing the same issue (I work in v0.5 which is the latest Bluemix Blockchain). Could you finally fix it?
I would appreciate if you could help me.
Thanks!

**Comment by ratnakar-asara** [comment]
@javierpruedas The latest Bluemix Blockchain service is based out of **Fabric V0.6** and **hfc0.6.x**
Can you please confirm if you are using the right hfc ?

**Comment by javierpruedas** [comment]
Yes @ratnakar-asara , I think I am in the right version. 

$npm list -g | grep hfc
├─┬ hfc@0.6.5

Is there something else you need to know or do you know other sample application that works?

**Comment by ratnakar-asara** [comment]
@javierpruedas Can you please send me the debug logs with the below command

> GRPC_TRACE=all DEBUG=hfc node helloblockchain.js

**Comment by javierpruedas** [comment]
@ratnakar-asara Sure. Admin enrolles properly, I send you the logs after that:

Enrolled admin sucecssfully
  hfc MemberServicesImpl.register: req={"enrollmentID":"JohnDoe1","account":"group1","affiliation":"00001"} +2ms
  hfc register {"id":{"id":"JohnDoe1"},"role":1,"attributes":[],"affiliation":"00001","registrar":{"id":{"id":"admin"},"roles":[],"delegateRoles":[]},"sig":{"type":0,"r":{"buffer":{"type":"Buffer","data":[55,48,48,57,56,54,49,50,52,52,52,51,48,49,51,53,57,57,52,50,55,50,57,54,53,51,55,51,49,56,54,50,52,55,50,56,52,57,55,51,51,54,52,57,55,54,50,53,48,48,49,50,57,52,54,54,53,53,52,55,57,50,50,56,54,50,48,51,52,48,49,57,48,48,52,56,57]},"offset":0,"markedOffset":-1,"limit":77,"littleEndian":false,"noAssert":false},"s":{"buffer":{"type":"Buffer","data":[50,53,54,53,57,56,54,56,52,57,54,55,51,55,55,50,57,49,56,54,51,52,55,51,54,52,52,51,49,48,56,51,52,54,48,50,50,53,52,52,50,49,52,56,57,51,54,54,50,52,48,48,52,54,51,48,49,57,56,52,57,50,56,49,52,48,52,53,51,50,55,55,54,57,56,52,57]},"offset":0,"markedOffset":-1,"limit":77,"littleEndian":false,"noAssert":false}}}: err={"code":2,"metadata":{"_internal_repr":{}}}, token=undefined +915ms
  hfc memberServices.register err=Error: Invalid affiliation group 00001, secret=null +2ms
/home/javier/workspace/SDK-Demo/helloblockchain.js:105
            if (err) throw Error(" Failed to register and enroll " + enrollName + ": " + err);
                     ^

Error:  Failed to register and enroll JohnDoe1: Error: Invalid affiliation group 00001
    at Error (native)
    at /home/javier/workspace/SDK-Demo/helloblockchain.js:105:28
    at /usr/lib/node_modules/hfc/lib/hfc.js:545:28
    at /usr/lib/node_modules/hfc/lib/hfc.js:787:24
    at /usr/lib/node_modules/hfc/lib/hfc.js:729:24
    at Object.callback (/usr/lib/node_modules/hfc/lib/hfc.js:1988:24)
    at /usr/lib/node_modules/hfc/node_modules/grpc/src/node/src/client.js:420:14

**Comment by ratnakar-asara** [comment]
@javierpruedas Seems you are using some old code base.
Can you please pull the latest code and try again.

`hfc MemberServicesImpl.register: req={"enrollmentID":"JohnDoe1","account":"group1","affiliation":"00001"} `

There is no user _JohnDoe1_ and the _affiliation_ used above is Invalid too in **FabricV0.6**
