### ISSUE TITLE
handshake exception on second try

### ISSUE THREAD

**Issue by KennethNagin** [IBM-Blockchain/SDK-Demo#18]
The first time I run  node helloblackchain.js it succeeds.  The output is as expected.
However, if I run it again the result is a handshake exception.
The bluemix blockchain service was created today (Nov 30 2016)
I installed hfc@0.6.5

This is the error message that I am receiving:
E1130 14:15:34.514364191   10392 handshake.c:128]            Security handshake failed: {"created":"@1480508134.514318907","description":"Handshake read failed","file":"../src/core/lib/security/transport/handshake.c","file_line":237,"referenced_errors":[{"created":"@1480508134.514314734","description":"FD shutdown","file":"../src/core/lib/iomgr/ev_epoll_linux.c","file_line":948}]}
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error
    at ClientDuplexStream._emitStatusIfDone (/home/nagin/work/src/github.com/KennethNagin/SDK-Demo/node_modules/grpc/src/node/src/client.js:189:19)
    at ClientDuplexStream._readsDone (/home/nagin/work/src/github.com/KennethNagin/SDK-Demo/node_modules/grpc/src/node/src/client.js:158:8)
    at readCallback (/home/nagin/work/src/github.com/KennethNagin/SDK-Demo/node_modules/grpc/src/node/src/client.js:217:12)
E1130 14:15:34.633437400   10392 handshake.c:128]            Security handshake failed: {"created":"@1480508134.633417032","description":"Handshake read failed","file":"../src/core/lib/security/transport/handshake.c","file_line":237,"referenced_errors":[{"created":"@1480508134.633415044","description":"FD shutdown","file":"../src/core/lib/iomgr/ev_epoll_linux.c","file_line":948}]}

**Comment by KennethNagin** [comment]
Oddly,  sometime it succeeds!  But most of the time it fails.

**Comment by KennethNagin** [comment]
The problem no longer occurs.  I suppose it must have been a problem with the Bluemix Blockchain service.
