### ISSUE TITLE
Error: Identity or token does not match

### ISSUE THREAD

**Issue by reoim** [IBM-Blockchain/SDK-Demo#30]
I am following the README.md tutorial step by step. 

I could not run helloblockchain.js

```
node helloblockchain.js
```
And I got following error message. How can I fix it?

```
------------- ca-server, peers and event URL:PORT information: -------------

CA server Url : grpcs://dc1584ff73d24603bf0d80a2ce6f05d4-ca.us.blockchain.ibm.com:30004

Validating Peer0 : grpcs://dc1584ff73d24603bf0d80a2ce6f05d4-vp0.us.blockchain.ibm.com:30004
Validating Peer1 : grpcs://dc1584ff73d24603bf0d80a2ce6f05d4-vp3.us.blockchain.ibm.com:30004
Validating Peer2 : grpcs://dc1584ff73d24603bf0d80a2ce6f05d4-vp2.us.blockchain.ibm.com:30004
Validating Peer3 : grpcs://dc1584ff73d24603bf0d80a2ce6f05d4-vp1.us.blockchain.ibm.com:30004

Event Url on Peer0 : grpcs://dc1584ff73d24603bf0d80a2ce6f05d4-vp0.us.blockchain.ibm.com:31004
Event Url on Peer1 : grpcs://dc1584ff73d24603bf0d80a2ce6f05d4-vp3.us.blockchain.ibm.com:31004
Event Url on Peer2 : grpcs://dc1584ff73d24603bf0d80a2ce6f05d4-vp2.us.blockchain.ibm.com:31004
Event Url on Peer3 : grpcs://dc1584ff73d24603bf0d80a2ce6f05d4-vp1.us.blockchain.ibm.com:31004

-----------------------------------------------------------

/Users/pkgmgmt/workspace/SDK-Demo/helloblockchain.js:135
        if (err) throw Error("\nERROR: failed to enroll admin : " + err);
                 ^

Error:
ERROR: failed to enroll admin : Error: Identity or token does not match.
    at Error (native)
    at /Users/pkgmgmt/workspace/SDK-Demo/helloblockchain.js:135:24
    at /Users/pkgmgmt/workspace/SDK-Demo/node_modules/hfc/lib/hfc.js:523:28
    at /Users/pkgmgmt/workspace/SDK-Demo/node_modules/hfc/lib/hfc.js:756:24
    at Object.callback (/Users/pkgmgmt/workspace/SDK-Demo/node_modules/hfc/lib/hfc.js:2038:24)
    at /Users/pkgmgmt/workspace/SDK-Demo/node_modules/grpc/src/node/src/client.js:420:14
```

**Comment by reoim** [comment]
Never mind. I deleted old network and did it again on the new one. Everything work fine.
