### ISSUE TITLE
Unsupported versions of Node.js and npm cause installation failure

### ISSUE THREAD

**Issue by pfuntner** [IBM-Blockchain/SDK-Demo#31]
When installing the demo with  node.js v7.8.0 and npm  v4.2.0, these nastygrams appear:

```
../src/node/ext/byte_buffer.cc: In function ‘v8::Local grpc::node::MakeFastBuffer(v8::Local)’:
       ../src/node/ext/byte_buffer.cc:99:72: warning: ‘v8::Local v8::Function::NewInstance(int, v8::Local*) const’ is deprecated (declared at /home/vcap/.node-gyp/7.8.0/include/node/v8.h:3657): Use maybe version [-Wdeprecated-declarations]
       ^
       CXX(target) Release/obj.target/grpc_node/src/node/ext/call.o
       ../src/node/ext/call.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE grpc::node::Call::New(Nan::NAN_METHOD_ARGS_TYPE)’:
       ../src/node/ext/call.cc:616:20: error: ‘class v8::Object’ has no member named ‘SetHiddenValue’
       info.This()->SetHiddenValue(Nan::New("channel_").ToLocalChecked(),
       ^
       ../src/node/ext/call.cc:625:19: warning: ‘v8::Local v8::Function::NewInstance(int, v8::Local*) const’ is deprecated (declared at /home/vcap/.node-gyp/7.8.0/include/node/v8.h:3657): Use maybe version [-Wdeprecated-declarations]
       argc, argv);
       ^
       make: *** [Release/obj.target/grpc_node/src/node/ext/call.o] Error 1
       gyp ERR! build error
       gyp ERR! stack     at ChildProcess.onExit (/tmp/app/.cloudfoundry/node/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
       gyp ERR! stack     at emitTwo (events.js:106:13)
       gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
       gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
       gyp ERR! command "/tmp/app/.cloudfoundry/node/bin/node" "/tmp/app/.cloudfoundry/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/tmp/app/node_modules/grpc/src/node/extension_binary/grpc_node.node" "--module_name=grpc_node" "--module_path=/tmp/app/node_modules/grpc/src/node/extension_binary"
       gyp ERR! cwd /tmp/app/node_modules/grpc
       gyp ERR! node -v v7.8.0
       gyp ERR! node-gyp -v v3.5.0
       node-pre-gyp ERR! build error
       node-pre-gyp ERR! stack Error: Failed to execute '/tmp/app/.cloudfoundry/node/bin/node /tmp/app/.cloudfoundry/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/tmp/app/node_modules/grpc/src/node/extension_binary/grpc_node.node --module_name=grpc_node --module_path=/tmp/app/node_modules/grpc/src/node/extension_binary' (1)
       node-pre-gyp ERR! stack     at ChildProcess. (/tmp/app/node_modules/grpc/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
       node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
       node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
       node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
       node-pre-gyp ERR! System Linux 4.4.0-45-generic
       node-pre-gyp ERR! command "/tmp/app/.cloudfoundry/node/bin/node" "/tmp/app/node_modules/grpc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
       node-pre-gyp ERR! cwd /tmp/app/node_modules/grpc
       node-pre-gyp ERR! node -v v7.8.0
       node-pre-gyp ERR! not ok
       Hello-Blockchain@0.0.1 /tmp/app
       └── d@1.0.0  extraneous
      
       npm ERR! Linux 4.4.0-45-generic
       npm ERR! node v7.8.0
       npm ERR! npm  v4.2.0
       npm ERR! code ELIFECYCLE
       npm ERR! errno 1
       npm ERR! Exit status 1
       npm ERR!
       npm ERR! Failed at the grpc@1.0.0 install script 'node-pre-gyp install --fallback-to-build'.
       npm ERR! Make sure you have the latest version of node.js and npm installed.
       npm ERR! If you do, this is most likely a problem with the grpc package,
       npm ERR! not with npm itself.
       npm ERR! Tell the author that this fails on your system:
       npm ERR!     node-pre-gyp install --fallback-to-build
       npm ERR! You can get information on how to open an issue for this project with:
       npm ERR!     npm bugs grpc
       npm ERR! Or if that isn't available, you can get their info via:
       npm ERR!     npm owner ls grpc
       npm ERR! There is likely additional logging output above.
      
       npm ERR! Please include the following file with any support request:
       npm ERR!     /tmp/app/.npm/_logs/2017-04-25T06_56_16_946Z-debug.log
-----> Build failed
```

The SDK Demo probably requires a more stable version.  We might want to recommend using the LTS (long term support) version of Node.js and npm.  As of today, that is Node v6.10.2 which includes npm 3.10.10.

**Comment by ghost** [comment]
for now, I tried to fix it by:
npm install -g  n
sudo n 6.10.2
